### ISSUE TITLE
Error Running Lambda Guard

### ISSUE THREAD

**Issue by chrismrgn** [Skyscanner/LambdaGuard#42]
We're running LambdaGuard using your library, but it stopped working in late December 2021.

We run it from a Github Action (below), which was running successfully each week

```
name: Lambda Guard
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * SUN" # every Sunday at midnight

jobs:
  lambda-guard:
    name: Run LambdaGuard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout LambdaGuard
        uses: actions/checkout@v2
        with:
          repository: skyscanner/lambdaguard
      - name: Python Version
        run: |
            python --version
      - name: Build LambdaGuard
        run: |
            sudo make install
      - name: Run LambdaGuard
        run: |
            lambdaguard --verbose --keys  ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: LambdaGuard Report
          path: lambdaguard_output/report.html
```

We now see an error  in step `Run LambdaGuard` with the following output

```
Run lambdaguard --verbose --keys  *** ***
  lambdaguard --verbose --keys  *** ***
  shell: /usr/bin/bash -e {0}
Traceback (most recent call last):
  File "/usr/bin/lambdaguard", line 33, in <module>
    sys.exit(load_entry_point('LambdaGuard', 'console_scripts', 'lambdaguard')())
  File "/usr/bin/lambdaguard", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: LambdaGuard
Error: Process completed with exit code 1.
```

Outputs of other steps are as follows

Build LambdaGuard

```
Run sudo make install
  sudo make install
  shell: /usr/bin/bash -e {0}
pip3 install -e .
Obtaining file:///home/runner/work/siberia-aws-middleware/siberia-aws-middleware
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from LambdaGuard==2.4.3) (2.22.0)
Collecting boto3
  Downloading boto3-1.20.26-py3-none-any.whl (131 kB)
Collecting argparse
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting botocore<1.24.0,>=1.23.26
  Downloading botocore-1.23.26-py3-none-any.whl (8.5 MB)
Collecting jmespath<1.0.0,>=0.7.1
  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting s3transfer<0.6.0,>=0.5.0
  Downloading s3transfer-0.5.0-py3-none-any.whl (79 kB)
Collecting python-dateutil<3.0.0,>=2.1
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /usr/lib/python3/dist-packages (from botocore<1.24.0,>=1.23.26->boto3->LambdaGuard==2.4.3) (1.25.8)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.24.0,>=1.23.26->boto3->LambdaGuard==2.4.3) (1.14.0)
Installing collected packages: python-dateutil, jmespath, botocore, s3transfer, boto3, argparse, LambdaGuard
  Running setup.py develop for LambdaGuard
Successfully installed LambdaGuard argparse-1.4.0 boto3-1.20.26 botocore-1.23.26 jmespath-0.10.0 python-dateutil-2.8.2 s3transfer-0.5.0
```

Python Version

```
Run python --version
  python --version
  shell: /usr/bin/bash -e {0}
Python 3.8.10
```

Thank you for any help you can provide
